# Default configuration for RAG Document Optimizer

document_types:
  word:
    extension: ".docx"
    chunk_size: 512
    chunk_overlap: 50

directories:
  input: "./sample_docs"  # Directory to search for documents
  output: "./optimized_chunks"  # Directory to save optimized chunks (optional)

# Add more document types here in the future, e.g.:
# pdf:
#   extension: ".pdf"
#   chunk_size: 600
#   chunk_overlap: 100